import type { DeityMeta } from "@/types/content";

export const medziojnaMeta: DeityMeta = {
  slug: "medziojna",
  name: "Medziojna",
  domain: "God",
  epithet: {
    en: "Goddess of the Hunt",
    lt: "Medžioklės deivė",
    lv: "Medību dieviete",
  },
  summary: {
    en: "Medziojna is the Lithuanian goddess of the hunt and the chase, invoked by hunters for fortune and swift pursuit of game.",
    lt: "Medziojna yra lietuvių medžioklės ir vijimosi deivė, kurią šaukiasi medžiotojai sėkmingai garybai.",
    lv: "Medziojna ir lietuviešu medību un vajāšanas dieviete, ko mednieki piesauc par veiksmi.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  altNames: {
    en: "Medziojna",
    lt: "Medziojna",
    lv: "Medziojna",
  },
  keywords: ["Hunting", "Chase", "Fortune"],
  gallery: [],
  locations: [
    {
      id: "sambia-hunting-forest",
      name: "Sambian Sacred Hunting Forest",
      coordinates: [54.85, 20.4],
      region: "Old Prussia",
      description: "Dense primeval forest in the Sambian peninsula where Prussian hunters offered prayers before the hunt.",
      siteType: "Sacred groves",
      aura: "moss",
      deity: "medziojna",
      significance: "Hunters invoked Medziojna here for swift pursuit and safe return, leaving game offerings at forest shrines.",
    },
  ],
  materialLegacy: [],
  symbols: [
    { label: "Sacred symbols", detail: "Bow, Hunting horn, Spear" },
  ],
  regionDetails: { en: "Samogitia", lt: "Žemaitija", lv: "Žemaitija" },
  tribe: { en: "Samogitian Lithuanians", lt: "Žemaičiai", lv: "Samogitijas lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const ejagusteMeta: DeityMeta = {
  slug: "ejaguste",
  name: "Ejagustė",
  domain: "God",
  epithet: {
    en: "Spirit of Hunting Fortune",
    lt: "Medžioklės sėkmės dvasia",
    lv: "Medību veiksmes gars",
  },
  summary: {
    en: "Ejagustė is the Lithuanian spirit of hunting luck, ensuring favorable outcomes in the chase.",
    lt: "Ejagustė yra lietuvių medžioklės sėkmės dvasia, užtikrinanti palankų medžioklės rezultatą.",
    lv: "Ejaguste ir lietuviešu medību veiksmes gars, kas nodrošina labvēlīgus medību rezultātus.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  altNames: {
    en: "Ejagustė",
    lt: "Ejagustė",
    lv: "Ejaguste",
  },
  keywords: ["Hunting luck", "Fortune", "Chase"],
  gallery: [],
  locations: [
    {
      id: "sambia-bird-clearing",
      name: "Sambian Forest Clearing Shrine",
      coordinates: [54.88, 20.6],
      region: "Old Prussia",
      description: "An open forest clearing in Old Prussia where birds were observed as omens and offerings made to the spirit of hunting luck.",
      siteType: "Sacred groves",
      aura: "moss",
      deity: "ejaguste",
      significance: "Hunters gathered here to watch bird flight patterns as omens before setting out, invoking Ejagustė for favorable fortune.",
    },
  ],
  materialLegacy: [],
  symbols: [
    { label: "Sacred symbols", detail: "Bow, Footsteps, Game animal" },
  ],
  regionDetails: { en: "Samogitia", lt: "Žemaitija", lv: "Žemaitija" },
  tribe: { en: "Samogitian Lithuanians", lt: "Žemaičiai", lv: "Samogitijas lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const silinytisMeta: DeityMeta = {
  slug: "silinytis",
  name: "Šilinytis",
  domain: "God",
  epithet: {
    en: "Guardian of the Pine Forest",
    lt: "Pušyno saugotojas",
    lv: "Priežu meža sargs",
  },
  summary: {
    en: "Šilinytis is the Lithuanian spirit of the pine forest, guardian of the sandy-soiled šilas groves and the life that thrives within them.",
    lt: "Šilinytis yra lietuvių pušyno dvasia, šilų globėjas ir jų augmenijos saugotojas.",
    lv: "Šilinytis ir lietuviešu priežu meža gars, kas sargā smilšaino šilu birzis un to dzīvību.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  altNames: {
    en: "Šilinytis",
    lt: "Šilinytis",
    lv: "Šilinytis",
  },
  keywords: ["Pine forest", "Resin", "Heather", "Moss"],
  gallery: [],
  locations: [
    {
      id: "sambia-pine-grove",
      name: "Sambian Pine Heathland",
      coordinates: [54.9, 20.55],
      region: "Old Prussia",
      description: "Sandy-soiled pine heathland (šilas) in the Sambian peninsula, home of the guardian spirit of fir and pine forests.",
      siteType: "Sacred groves",
      aura: "moss",
      deity: "silinytis",
      significance: "Šilinytis was believed to dwell in these ancient pine groves, accepting resin and pine-cone offerings from those who felled trees.",
    },
  ],
  materialLegacy: [],
  symbols: [
    { label: "Sacred symbols", detail: "Pine cone, Heather, Moss, Resin" },
  ],
  regionDetails: { en: "Samogitia / Aukštaitija", lt: "Žemaitija / Aukštaitija", lv: "Žemaitija / Aukštaitija" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const giraitisMeta: DeityMeta = {
  slug: "giraitis",
  name: "Giraitis",
  domain: "God",
  epithet: {
    en: "Guardian of the Sacred Grove",
    lt: "Šventosios giraitės saugotojas",
    lv: "Svētā birzs sargs",
  },
  summary: {
    en: "Giraitis is the Lithuanian spirit of sacred groves, presiding over the sanctified clusters of trees that communities held inviolable.",
    lt: "Giraitis yra lietuvių šventųjų giraitių dvasia, valdantis sakralias medžių grupes ir jų ramybę.",
    lv: "Giraitis ir lietuviešu svēto birzu gars, kas valda apvienotajās koku grupās.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  altNames: {
    en: "Giraitis",
    lt: "Giraitis",
    lv: "Giraitis",
  },
  keywords: ["Sacred grove", "Trees", "Forest peace"],
  gallery: [],
  locations: [
    {
      id: "aukstaitija-sacred-birch-grove",
      name: "Aukštaitija Sacred Birch Grove",
      coordinates: [55.55, 25.4],
      region: "Lithuania",
      description: "An ancient cluster of birch trees in Aukštaitija held inviolable by the community as the dwelling of the grove spirit Giraitis.",
      siteType: "Sacred groves",
      aura: "green",
      deity: "giraitis",
      significance: "No tree could be felled here without ritual permission; communities gathered at this grove for seasonal rites and offerings to the forest spirit.",
    },
  ],
  materialLegacy: [],
  symbols: [
    { label: "Sacred symbols", detail: "Oak branch, Birch catkin, Sacred grove boundary" },
  ],
  regionDetails: { en: "Samogitia / Pan-Lithuanian", lt: "Žemaitija / visos Lietuvos", lv: "Žemaitija / visas Lietuvas" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "16th–17th Century Records", lt: "XVI–XVII a. šaltiniai", lv: "16.–17. gadsimta avoti" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "Mierzyński, Antoni: Mythologiae Lituanicae Monumenta (1892)",
  ],
};

export const ugunsMateMetaData: DeityMeta = {
  slug: "uguns-mate",
  name: "Uguns māte",
  domain: "God",
  epithet: {
    en: "Mother of Fire and the Hearth",
    lt: "Ugnies ir židinio motina",
    lv: "Uguns un pavarda māte",
  },
  summary: {
    en: "Uguns māte is the Latvian goddess of the sacred hearth fire, guardian of the family's warmth, health, and spiritual continuity.",
    lt: "Uguns māte yra latvių šventosios krosninės ugnies deivė, šeimos šilumos ir dvasinės tęstinumo saugotoja.",
    lv: "Uguns māte ir latvju svētās pavarda uguns dieviete, ģimenes siltuma un garīgās turpinātības sargātāja.",
  },
  heroImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(180, 80, 40, 0.27)",
  accent: "#c05030",
  altNames: {
    en: "Uguns māte",
    lt: "Ugnies motina",
    lv: "Uguns māte",
  },
  keywords: ["Fire", "Hearth", "Home protection", "Family"],
  gallery: [],
  locations: [
    {
      id: "latvia-hearth-fire-site",
      name: "Latvian Farmstead Hearth Shrine",
      coordinates: [57.05, 25.1],
      region: "Latvia",
      description: "The central hearth of a traditional Latvian farmstead, kept perpetually alight as the sacred domain of Uguns māte.",
      siteType: "Hearth cult zones",
      aura: "amber",
      deity: "uguns-mate",
      significance: "Families offered the first portion of each meal to the hearth fire, and new brides were introduced to the flame upon entering the household.",
    },
  ],
  materialLegacy: [],
  symbols: [
    { label: "Sacred symbols", detail: "Hearth-stone, Golden flame, Salt-grain, Ash-pile" },
  ],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Uguns māte (enciklopedija.lv)",
  ],
};

export const majasMateMetaData: DeityMeta = {
  slug: "majas-mate",
  name: "Mājas māte",
  altNames: { en: "Mājas māte", lt: "Namų motina", lv: "Mājas māte" },
  domain: "God",
  epithet: {
    en: "Mother of the House",
    lt: "Namų motina",
    lv: "Mājas māte",
  },
  summary: {
    en: "Mājas māte is the Latvian spirit of the household, governing domestic harmony, children's health, and the luck that resides within family walls.",
    lt: "Mājas māte yra latvių namų dvasia, valdanti namų darną, vaikų sveikatą ir šeimos laimę.",
    lv: "Mājas māte ir latvju mājas gars, kas valda mājas harmoniju, bērnu veselību un ģimenes laimi.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["House", "Harmony", "Luck", "Children"],
  symbols: [
    { label: "Sacred symbols", detail: "Threshold, Key, Loom" },
  ],
  locations: [
    {
      id: "latvia-homestead-threshold",
      name: "Latvian Farmstead Threshold",
      coordinates: [57.0, 24.8],
      region: "Latvia",
      description: "The threshold and inner courtyard of a traditional Latvian farmstead, the liminal zone presided over by Mājas māte.",
      siteType: "Household ritual sites",
      aura: "amber",
      deity: "majas-mate",
      significance: "Ritual offerings were placed at the threshold when moving into a new home, and the spirit was appeased with bread and salt to ensure domestic harmony.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Mājas māte (enciklopedija.lv)",
  ],
};

export const pirtsMateMetaData: DeityMeta = {
  slug: "pirts-mate",
  name: "Pirts māte",
  altNames: { en: "Pirts māte", lt: "Pirties motina", lv: "Pirts māte" },
  domain: "God",
  epithet: {
    en: "Mother of the Bathhouse",
    lt: "Pirties motina",
    lv: "Pirts māte",
  },
  summary: {
    en: "Pirts māte is the guardian spirit of the Latvian sauna, presiding over cleansing, childbirth, and the threshold between physical and spiritual wellness.",
    lt: "Pirts māte yra latvių pirties saugotoja, valdanti valymo ritualus, gimdymą ir ribą tarp kūno ir dvasinės sveikatos.",
    lv: "Pirts māte ir latvju pirts sargātāja, kas valda attīrīšanas rituālus, dzemdības un robežu starp fizisko un garīgo veselību.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Bathhouse", "Cleansing", "Childbirth", "Healing"],
  symbols: [
    { label: "Sacred symbols", detail: "Birch-branch slota, Steam, Wooden bucket" },
  ],
  locations: [
    {
      id: "latvia-bathhouse-ritual",
      name: "Latvian Ritual Bathhouse (Pirts)",
      coordinates: [57.1, 25.0],
      region: "Latvia",
      description: "A traditional Latvian pirts (sauna-bathhouse) used for ritual cleansing, healing, and childbirth ceremonies overseen by Pirts māte.",
      siteType: "Household ritual sites",
      aura: "mist",
      deity: "pirts-mate",
      significance: "Women gave birth in the pirts under Pirts māte's protection, and weekly steam baths were considered a spiritual purification rite.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Pirts māte (enciklopedija.lv)",
  ],
};

export const lopuMateMetaData: DeityMeta = {
  slug: "lopu-mate",
  name: "Lopu māte",
  altNames: { en: "Lopu māte", lt: "Gyvulių motina", lv: "Lopu māte" },
  domain: "God",
  epithet: {
    en: "Mother of Livestock",
    lt: "Gyvulių motina",
    lv: "Lopu māte",
  },
  summary: {
    en: "Lopu māte is the Latvian guardian of farm animals, walking through barns to count and protect the herds through each season.",
    lt: "Lopu māte yra latvių ūkio gyvulių saugotoja, einanti per tvartelį skaičiuoti ir saugoti bandas kiekvienais metų laikais.",
    lv: "Lopu māte ir latvju lauksaimniecības dzīvnieku sargātāja, staigājot pa stalliem, skaitot un sargājot ganāmpulkus cauri gadalaikiem.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Livestock", "Cattle", "Seasonal protection", "Herds"],
  symbols: [
    { label: "Sacred symbols", detail: "Barn-key, Woven hay, Cattle" },
  ],
  locations: [
    {
      id: "latvia-cattle-pasture",
      name: "Latvian Seasonal Cattle Pasture",
      coordinates: [56.9, 24.5],
      region: "Latvia",
      description: "Open pasture fields of central Latvia where cattle herds grazed under the seasonal protection of Lopu māte.",
      siteType: "Field altars",
      aura: "green",
      deity: "lopu-mate",
      significance: "Offerings of bread and salt were left at pasture boundaries before animals were driven out in spring, asking Lopu māte to guard each beast through the grazing season.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Agricultural regions)", lt: "Latvija (žemdirbystės regionai)", lv: "Latvija (lauksaimniecības reģioni)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "LNE: Lopu māte (enciklopedija.lv)",
    "Kursīte, Janīna: Mītiskais folklorā (1999)",
  ],
};

export const puschkaitisMeta: DeityMeta = {
  slug: "puschkaitis",
  name: "Puschkaitis",
  altNames: { en: "Puschkaitis", lt: "Puschkaitis", lv: "Puškaitss" },
  domain: "God",
  epithet: {
    en: "Earth Lord beneath the Elder Tree",
    lt: "Žemės valdovas po juodalksniu",
    lv: "Zemes kungs zem melnalkšņa",
  },
  summary: {
    en: "Puschkaitis is the Old Prussian deity of the earth beneath trees, ruler of the Kaukai and Markopoles household spirits who bring agricultural abundance.",
    lt: "Puschkaitis yra senovės prūsų žemės po medžiais dievas, Kaukų ir Markopolių namų dvasinių valdovas.",
    lv: "Puschkaitis ir vecprūšu zemes zem kokiem dievs, Kaukai un Markopoles mājas garu valdnieks.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Earth", "Elder tree", "Fertility", "Household abundance"],
  symbols: [
    { label: "Sacred symbols", detail: "Elder tree, Stone altar, Porridge bowl" },
  ],
  locations: [
    {
      id: "sambia-elder-tree-site",
      name: "Sambian Elder Tree Sanctuary",
      coordinates: [54.92, 20.45],
      region: "Old Prussia",
      description: "An ancient elder tree in the Sambian peninsula under which Puschkaitis was said to dwell, with a stone altar at its roots.",
      siteType: "\"World tree\" analog sites",
      aura: "moss",
      deity: "puschkaitis",
      significance: "Households left bowls of porridge and beer beneath the elder tree to propitiate Puschkaitis and his Kaukai spirits, ensuring barn abundance.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Old Prussia (Sambia, Sudovia)", lt: "Senoji Prūsija (Semba, Sūduva)", lv: "Senprūsija (Sambija, Sūdava)" },
  tribe: { en: "Old Prussian (Prūsai)", lt: "Senovės prūsai (Prūsai)", lv: "Vecprūši (Prūsai)" },
  period: { en: "16th–17th Century Records", lt: "XVI–XVII a. šaltiniai", lv: "16.–17. gadsimta avoti" },
  references: [
    "Sudauer Büchlein / Sudovian Book (16th c.)",
    "Praetorius, Matthäus: Deliciae Prussicae (ms. ~1690)",
    "Mannhardt, Wilhelm: Letto-Preussische Götterlehre (1936)",
  ],
};

export const curchoMeta: DeityMeta = {
  slug: "curcho",
  name: "Curcho",
  altNames: { en: "Curcho", lt: "Kurkė", lv: "Kurķis" },
  domain: "God",
  epithet: {
    en: "Spirit of the Harvest and Abundance",
    lt: "Derliaus ir gausos dvasia",
    lv: "Ražas un pārticības gars",
  },
  summary: {
    en: "Curcho is the Old Prussian harvest spirit, a ritual personification of the grain's vital force to whom the first-fruits of every sowing were offered.",
    lt: "Curcho yra senovės prūsų derliaus dvasia, ritualinė javų gyvybinės jėgos personifikacija, kuriai aukojami pirmieji javai.",
    lv: "Curcho ir vecprūšu ražas gars, rituāla graudu dzīvīgā spēka personifikācija, kuram tiek ziedoti pirmie ražas augļi.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Harvest", "Grain", "First-fruits", "Agricultural cycle"],
  symbols: [
    { label: "Sacred symbols", detail: "Grain sheaf, Flour, Beer pitcher, Woven straw figure" },
  ],
  locations: [
    {
      id: "prussia-harvest-field",
      name: "Old Prussian Harvest Field Altar",
      coordinates: [54.5, 20.8],
      region: "Old Prussia",
      description: "An open harvest field in Old Prussia where the first sheaves of grain were ceremonially offered to Curcho each autumn.",
      siteType: "Field altars",
      aura: "amber",
      deity: "curcho",
      significance: "Farmers brought the first-fruits of every harvest to this field altar, pouring beer and placing grain offerings to ensure Curcho's continued blessing.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Old Prussia", lt: "Senoji Prūsija", lv: "Senprūsija" },
  tribe: { en: "Old Prussian (Prūsai)", lt: "Senovės prūsai (Prūsai)", lv: "Vecprūši (Prūsai)" },
  period: { en: "16th–17th Century Records", lt: "XVI–XVII a. šaltiniai", lv: "16.–17. gadsimta avoti" },
  references: [
    "Sudauer Büchlein / Sudovian Book (16th c.)",
    "Hartknoch, Christoph: Alt- und neues Prussien (1684)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai (1996)",
  ],
};

// Batch 6
export const pliuktisMeta: DeityMeta = {
  slug: "pliuktis",
  name: "Pliuktis",
  altNames: { en: "Pliuktis", lt: "Pliuktis", lv: "Pliuktis" },
  domain: "God",
  epithet: {
    en: "God of Rain",
    lt: "Lietaus dievas",
    lv: "Lietus dievs",
  },
  summary: {
    en: "Pliuktis is the Lithuanian god of rain, invoked during drought to send the life-giving precipitation needed for crops.",
    lt: "Pliuktis yra lietuvių lietaus dievas, šaukiamas sausrų metu siųsti gyvybę teikiančio lietaus javams.",
    lv: "Pliuktis ir lietuviešu lietus dievs, piesaukts sausuma laikā, lai sūtītu dzīvību dodošos nokrišņus ražai.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Rain", "Precipitation", "Crops", "Drought relief"],
  symbols: [
    { label: "Sacred symbols", detail: "Water drop, Splashing water, Rain cloud, Sieve" },
  ],
  locations: [
    {
      id: "samogitia-rain-hilltop",
      name: "Samogitian Rain Ritual Hilltop",
      coordinates: [55.85, 22.4],
      region: "Lithuania",
      description: "A hilltop in Samogitia where communities gathered during drought to perform rain-calling rites invoking Pliuktis.",
      siteType: "Sacred hilltops",
      aura: "mist",
      deity: "pliuktis",
      significance: "During droughts, ritual processions climbed this hill to pour water libations and call upon Pliuktis for life-giving rains on the grain fields.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Samogitia", lt: "Žemaitija", lv: "Žemaitija" },
  tribe: { en: "Samogitian Lithuanians", lt: "Žemaičiai", lv: "Samogitijas lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const kaupolisMeta: DeityMeta = {
  slug: "kaupolis",
  name: "Kaupolis",
  altNames: { en: "Kaupolis", lt: "Kaupolis", lv: "Kaupolis" },
  domain: "God",
  epithet: {
    en: "Deity of the Flourishing Earth and Midsummer",
    lt: "Klestinčios žemės ir vasaros saulėgrįžos dievas",
    lv: "Ziedošās zemes un vasaras saulgriežu dievs",
  },
  summary: {
    en: "Kaupolis and Kupolė are the Lithuanian deities of springtime growth, blooming vegetation, and the midsummer solstice festival.",
    lt: "Kaupolis ir Kupolė yra lietuvių pavasario augmenijos ir vasaros saulėgrįžos šventės dievybės.",
    lv: "Kaupolis un Kupolė ir lietuviešu pavasara augšanas un vasaras saulgriežu svētku dievības.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Midsummer", "Blooming", "Solstice", "Herbs", "Growth"],
  symbols: [
    { label: "Sacred symbols", detail: "Spring flower, Midsummer wreath, Tribranced pole, Morning dew" },
  ],
  locations: [
    {
      id: "lithuania-midsummer-field",
      name: "Lithuanian Midsummer Celebration Field",
      coordinates: [55.4, 24.2],
      region: "Lithuania",
      description: "An open meadow in central Lithuania used for Rasos (Midsummer) festival celebrations, sacred to Kaupolis and Kupolė.",
      siteType: "Seasonal festival locations",
      aura: "green",
      deity: "kaupolis",
      significance: "On the eve of the summer solstice, young people wove herb wreaths and lit bonfires here to honor the deity of blooming vegetation and midsummer abundance.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Pan-Lithuanian)", lt: "Lietuva (visos)", lv: "Lietuva (visā)" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "Proto-Baltic / 16th Century Records", lt: "Protobaltiška / XVI a. šaltiniai", lv: "Protobaltu / 16. gadsimta avoti" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "Greimas, Algirdas J.: Tautos atminties beieškant (1990)",
  ],
};

export const lygynaMeta: DeityMeta = {
  slug: "lygyna",
  name: "Lygyna",
  altNames: { en: "Lygyna", lt: "Lygyna", lv: "Lygyna" },
  domain: "God",
  epithet: {
    en: "Goddess of Field Purity",
    lt: "Laukų tyrumo deivė",
    lv: "Lauku tīrības dieviete",
  },
  summary: {
    en: "Lygyna is the Lithuanian goddess invoked to prevent weeds and cockle from contaminating grain fields, ensuring a pure and bountiful harvest.",
    lt: "Lygyna yra lietuvių deivė, šaukiama apsaugoti javų laukus nuo raugių, užtikrinant tyrą derlių.",
    lv: "Lygyna ir lietuviešu dieviete, kas tiek piesaukta, lai novērstu nezāles graudu laukos un nodrošinātu tīru ražu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Field purity", "Weeds", "Grain health", "Agriculture"],
  symbols: [
    { label: "Sacred symbols", detail: "Weed cockle, Grain ear, Sieve, Level field" },
  ],
  locations: [
    {
      id: "samogitia-grain-field-altar",
      name: "Samogitian Grain Field Altar",
      coordinates: [55.8, 22.5],
      region: "Lithuania",
      description: "A ritual stone at the edge of grain fields in Samogitia where Lygyna was invoked to keep fields free of weeds and cockle.",
      siteType: "Field altars",
      aura: "green",
      deity: "lygyna",
      significance: "Before weeding season, farmers left offerings at this stone asking Lygyna to bless their fields with purity and a clean, bountiful harvest.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Samogitia", lt: "Žemaitija", lv: "Žemaitija" },
  tribe: { en: "Samogitian Lithuanians", lt: "Žemaičiai", lv: "Samogitijas lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const rugucysMeta: DeityMeta = {
  slug: "ruguczys",
  name: "Ruguczys",
  altNames: { en: "Ruguczys", lt: "Rugučys", lv: "Rugučys" },
  domain: "God",
  epithet: {
    en: "God of Fermentation and Yeast",
    lt: "Rūgimo ir raugo dievas",
    lv: "Rūgšanas un rauga dievs",
  },
  summary: {
    en: "Ruguczys is the Lithuanian deity of fermentation, souring, and yeast, guardian of the living transformations in bread-making and brewing.",
    lt: "Rugučys yra lietuvių rūgimo, rūgštimo ir raugo dievas, gyvo virtimo duonoje ir aluje globėjas.",
    lv: "Rugučys ir lietuviešu rūgšanas, skābuma un rauga dievs, kas sargā dzīvās pārmaiņas maizes cepšanā un alus brūvēšanā.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Fermentation", "Yeast", "Sourdough", "Brewing", "Transformation"],
  symbols: [
    { label: "Sacred symbols", detail: "Sourdough bread, Yeast bubbles, Wooden dough bowl, Hops" },
  ],
  locations: [
    {
      id: "prussia-rye-brewery",
      name: "Samogitian Rye Brewery and Field",
      coordinates: [55.9, 22.5],
      region: "Lithuania",
      description: "Rye fields and communal brewery sites in Samogitia where Ruguczys was honored during grain fermentation and brewing rites.",
      siteType: "Communal feast sites",
      aura: "amber",
      deity: "ruguczys",
      significance: "Brewers and bakers propitiated Ruguczys before souring dough and brewing rye beer, offering the first cup to ensure successful fermentation.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Samogitia", lt: "Žemaitija", lv: "Žemaitija" },
  tribe: { en: "Samogitian Lithuanians", lt: "Žemaičiai", lv: "Samogitijas lietuvieši" },
  period: { en: "16th Century (Recorded by Łasicki)", lt: "XVI a. (Lasickio paminėta)", lv: "16. gadsimts (Łasicki pierakstīts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const biruteMeta: DeityMeta = {
  slug: "birute",
  name: "Birutė",
  altNames: { en: "Birutė", lt: "Birutė", lv: "Birutė" },
  domain: "Person",
  epithet: {
    en: "Sacred Priestess and Duchess of Lithuania",
    lt: "Šventoji vaidilutė ir Lietuvos kunigaikštienė",
    lv: "Svētā priestere un Lietuvas hercogiene",
  },
  summary: {
    en: "Birutė was the sacred priestess of Palanga who became wife of Grand Duke Kęstutis and mother of Vytautas the Great, venerated as a guardian spirit of the Lithuanian coast.",
    lt: "Birutė buvo Palangos šventoji vaidilutė, tapusi Didžiojo kunigaikščio Kęstučio žmona ir Vytauto Didžiojo motina, gerbiama kaip Lietuvos pakrantės saugotoja.",
    lv: "Birutė bija Palangas svētā priestere, kas kļuva par Lielkņaza Kęstutis sievu un Vytautas Lielā māti, cienīta kā Lietuvas piekrastes sargātāja.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Sacred fire", "Devotion", "Ancestry", "Priesthood"],
  symbols: [
    { label: "Sacred symbols", detail: "Sacred flame, Palanga hill, White linden, Amber necklace" },
  ],
  locations: [
    {
      id: "palanga-birute-hill",
      name: "Birutė Hill, Palanga",
      coordinates: [55.93, 21.07],
      region: "Lithuania",
      description: "A coastal hill in Palanga where the sacred vestal fire burned, tended by the priestess Birutė who later became Duchess of Lithuania.",
      siteType: "Ritual fire sites",
      aura: "amber",
      deity: "birute",
      significance: "The eternal fire of Perkūnas was kept alight here by vestal priestesses; Birutė's hill became a pilgrimage site venerated through the medieval period.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Palanga (Coastal Samogitia)", lt: "Palanga (Žemaitijos pakrantė)", lv: "Palanga (Samogitijas piekraste)" },
  tribe: { en: "Samogitians / Curonians", lt: "Žemaičiai / Kuršiai", lv: "Samogitijas / Kureši" },
  period: { en: "14th Century (Historical) / 15th–16th Century (Cult)", lt: "XIV a. (istorinė) / XV–XVI a. (kultas)", lv: "14. gadsimts (vēsturiska) / 15.–16. gadsimts (kults)" },
  references: [
    "Bychowiec Chronicle (16th Century MS)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 4 (2005)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const pienaMateMetaData: DeityMeta = {
  slug: "piena-mate",
  name: "Piena māte",
  altNames: { en: "Piena māte", lt: "Piena māte", lv: "Piena māte" },
  domain: "God",
  epithet: {
    en: "Mother of Milk",
    lt: "Pieno motina",
    lv: "Piena māte",
  },
  summary: {
    en: "Piena māte is the Latvian guardian of milk and dairy production, invoked to protect the milk's purity and the health of milking animals.",
    lt: "Piena māte yra latvių pieno ir pienininkystės globėja, šaukiama saugoti pieno tyrumą ir melžiamų gyvulių sveikatą.",
    lv: "Piena māte ir latvju piena un piensaimniecības sargātāja, ko piesauc, lai aizsargātu piena tīrību un slaucamo dzīvnieku veselību.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Milk", "Dairy", "Cattle", "Abundance"],
  symbols: [
    { label: "Sacred symbols", detail: "Milk pail, White cow, Cream pitcher, Woven cloth" },
  ],
  locations: [
    {
      id: "latvia-dairy-pasture",
      name: "Latvian Dairy Pasture Shrine",
      coordinates: [56.95, 24.7],
      region: "Latvia",
      description: "A pasture and dairy site in central Latvia where Piena māte was invoked to protect the purity and abundance of milk.",
      siteType: "Field altars",
      aura: "green",
      deity: "piena-mate",
      significance: "Dairymaids offered the first pail of milk each morning at a meadow stone shrine, asking Piena māte to protect their cows from illness and ensure rich cream.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Piena māte (enciklopedija.lv)",
  ],
};

export const vilkuMateMetaData: DeityMeta = {
  slug: "vilku-mate",
  name: "Vilku māte",
  altNames: { en: "Vilku māte", lt: "Vilkų motina", lv: "Vilku māte" },
  domain: "God",
  epithet: {
    en: "Mother of Wolves",
    lt: "Vilkų motina",
    lv: "Vilku māte",
  },
  summary: {
    en: "Vilku māte is the ambivalent Latvian deity who is both the ruling spirit of wolves and the protector of livestock against them.",
    lt: "Vilku māte yra dviprasmiška latvių dievybė, kuri yra ir vilkų valdovė, ir gyvulių apsaugotoja nuo jų.",
    lv: "Vilku māte ir neviennozīmīga latvju dievība, kas ir gan vilku valdniece, gan mājlopu aizsargātāja pret tiem.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Wolves", "Livestock protection", "Wild boundary", "Mediation"],
  symbols: [
    { label: "Sacred symbols", detail: "Wolf paw, Sheepfold gate, Forest boundary" },
  ],
  locations: [
    {
      id: "latvia-forest-edge-wolves",
      name: "Latvian Forest Edge Wolf Territory",
      coordinates: [57.2, 25.6],
      region: "Latvia",
      description: "The boundary between farmland and deep forest in Vidzeme, Latvia, where Vilku māte was said to command her wolf packs.",
      siteType: "Sacred groves",
      aura: "mist",
      deity: "vilku-mate",
      significance: "Farmers left offerings at the forest edge at the start of each season, petitioning Vilku māte to keep her wolves from attacking livestock in exchange for a portion of meat.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Vilku māte (enciklopedija.lv)",
  ],
};

export const tirumaMateMetaData: DeityMeta = {
  slug: "tiruma-mate",
  name: "Tīruma māte",
  altNames: { en: "Tīruma māte", lt: "Dirvonų motina", lv: "Tīruma māte" },
  domain: "God",
  epithet: {
    en: "Mother of the Plowed Field",
    lt: "Suartos lauko motina",
    lv: "Tīruma māte",
  },
  summary: {
    en: "Tīruma māte is the Latvian goddess of the open arable land, guardian of the furrow and the soil's fertility across each plowing season.",
    lt: "Tīruma māte yra latvių ariamo lauko deivė, vagos ir dirvos derlingumo saugotoja kiekvieną arimo sezoną.",
    lv: "Tīruma māte ir latvju aramzemes dieviete, vagas un augsnes auglības sargātāja katrā aruma sezonā.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Plowed field", "Soil fertility", "Furrow", "Harvest"],
  symbols: [
    { label: "Sacred symbols", detail: "Plowing stick, First furrow, Grain ear, Dark soil" },
  ],
  locations: [
    {
      id: "latvia-ploughed-field",
      name: "Latvian Ploughed Field Ritual Site",
      coordinates: [56.8, 24.3],
      region: "Latvia",
      description: "An open arable field in Zemgale, Latvia, where Tīruma māte was honored at the start of each plowing season.",
      siteType: "Field altars",
      aura: "green",
      deity: "tiruma-mate",
      significance: "The farmer walked the first furrow reciting prayers to Tīruma māte, leaving grain seeds and a bread offering in the soil to bless the season's cultivation.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Agricultural regions)", lt: "Latvija (žemdirbystės regionai)", lv: "Latvija (lauksaimniecības reģioni)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "Kursīte, Janīna: Mītiskais folklorā (1999)",
  ],
};

export const kapuMateMetaData: DeityMeta = {
  slug: "kapu-mate",
  name: "Kapu māte",
  altNames: { en: "Kapu māte", lt: "Kapų motina", lv: "Kapu māte" },
  domain: "God",
  epithet: {
    en: "Mother of Graves",
    lt: "Kapų motina",
    lv: "Kapu māte",
  },
  summary: {
    en: "Kapu māte is the Latvian guardian of burial grounds, watching over the graves of the dead and the peace of those interred within them.",
    lt: "Kapu māte yra latvių kapinių saugotoja, sauganti mirusiųjų kapus ir jų ramybę.",
    lv: "Kapu māte ir latvju kapu sargātāja, kas uzrauga mirušo kapus un tur apglabāto mieru.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Graves", "Burial", "Dead", "Peace"],
  symbols: [
    { label: "Sacred symbols", detail: "Burial mound, Candle, Oak branch, Grave cross" },
  ],
  locations: [
    {
      id: "latvia-ancient-burial-ground",
      name: "Latvian Ancient Burial Ground",
      coordinates: [56.6, 27.2],
      region: "Latvia",
      description: "An ancient burial ground in Latgale watched over by Kapu māte, where families brought offerings to honor the dead.",
      siteType: "Burial/cremation sites",
      aura: "mist",
      deity: "kapu-mate",
      significance: "At autumn ancestor festivals, candles and food offerings were left at grave mounds for Kapu māte to ensure the departed rested in peace.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Kapu māte (enciklopedija.lv)",
  ],
};

export const celaMateMetaData: DeityMeta = {
  slug: "cela-mate",
  name: "Ceļa māte",
  altNames: { en: "Ceļa māte", lt: "Kelio motina", lv: "Ceļa māte" },
  domain: "God",
  epithet: {
    en: "Mother of the Road",
    lt: "Kelio motina",
    lv: "Ceļa māte",
  },
  summary: {
    en: "Ceļa māte is the Latvian guardian of travelers and roads, invoked before journeys to ensure safe passage and return.",
    lt: "Ceļa māte yra latvių keliautojų ir kelių saugotoja, šaukiama prieš keliones saugiam pervažiavimui ir sugrįžimui.",
    lv: "Ceļa māte ir latvju ceļotāju un ceļu sargātāja, ko piesauc pirms ceļojumiem, lai nodrošinātu drošu braucienu un atgriešanos.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Travel", "Roads", "Safety", "Return"],
  symbols: [
    { label: "Sacred symbols", detail: "Road stone, Walking stick, Sunrise, Crossroads" },
  ],
  locations: [
    {
      id: "latvia-ancient-crossroads",
      name: "Latvian Ancient Road Crossroads",
      coordinates: [56.85, 23.8],
      region: "Latvia",
      description: "A well-traveled crossroads on an ancient trade route in Kurzeme, Latvia, where Ceļa māte was invoked by departing travelers.",
      siteType: "Seasonal festival locations",
      aura: "sky",
      deity: "cela-mate",
      significance: "Travelers left small offerings of bread and coins at the crossroads stone before long journeys, asking Ceļa māte for safe passage and a sure return.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Latvia (Pan-Latvian)", lt: "Latvija (visos regionuose)", lv: "Latvija (visā Latvijā)" },
  tribe: { en: "Latvians", lt: "Latviai", lv: "Latvieši" },
  period: { en: "Archaic / Oral Tradition", lt: "Archajiška / žodinė tradicija", lv: "Arhaiskā / mutvārdu tradīcija" },
  references: [
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "Šmits, Pēteris: Latviešu mitoloģija (1918)",
    "LNE: Ceļa māte (enciklopedija.lv)",
  ],
};

// ─── Batch 7 ─────────────────────────────────────────────────────────────────

export const girstisMeta: DeityMeta = {
  slug: "girstis",
  name: "Girstis",
  altNames: { en: "Girstis", lt: "Girstis", lv: "Girstis" },
  domain: "God",
  epithet: {
    en: "Forest Spirit of the Thickets",
    lt: "Miško tankmių dvasia",
    lv: "Brikšņu meža gars",
  },
  summary: {
    en: "Girstis is a Lithuanian forest deity who guards the undergrowth and thickets of the sacred groves, documented by Jan Łasicki in his 16th-century catalogue of Samogitian gods.",
    lt: "Girstis yra lietuvių miško dvasia, saugojanti šventų girių tankmynus, užfiksuota Jano Lasickio XVI a. dievybių sąraše.",
    lv: "Girstis ir lietuviešu meža gars, kas sargā svēto birzu brikšņus, dokumentēts Jāņa Lasicija 16. gadsimta sarakstā.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Forest", "Thickets", "Undergrowth", "Sacred groves"],
  symbols: [
    { label: "Sacred symbols", detail: "Branch, Thicket, Forest shadow, Moss" },
  ],
  locations: [
    {
      id: "zemaitija-forest-thicket",
      name: "Žemaitija Sacred Forest Thicket",
      coordinates: [55.9, 22.3],
      region: "Lithuania",
      description: "Dense undergrowth and thickets at the heart of a sacred Samogitian grove, believed to be inhabited by Girstis.",
      siteType: "Sacred groves",
      aura: "moss",
      deity: "girstis",
      significance: "Community members left offerings at the thicket edge asking Girstis to keep the undergrowth untampered, believing the spirit punished those who entered without ritual permission.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const jundaMeta: DeityMeta = {
  slug: "junda",
  name: "Junda",
  altNames: { en: "Junda", lt: "Junda", lv: "Junda" },
  domain: "God",
  epithet: {
    en: "Goddess of War and Victory",
    lt: "Karo ir pergalės deivė",
    lv: "Kara un uzvaras dieviete",
  },
  summary: {
    en: "Junda is the Lithuanian goddess of war and conquest, embodying the fierce spirit of Baltic warriors, first systematized by 19th-century historian Teodor Narbutt.",
    lt: "Junda yra lietuvių karo ir pergalės deivė, įkūnijanti baltų karių narsą ir T. Narbyto XIX a. mitologijos rekonstrukcijoje.",
    lv: "Junda ir lietuviešu kara un uzvaras dieviete, kas iemieso senbaltu karotāju drosmi un 19. gadsimta mitoloģijas rekonstrukcijās.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["War", "Victory", "Conquest", "Battle"],
  symbols: [
    { label: "Sacred symbols", detail: "Sword, Shield, Spear, Victory wreath" },
  ],
  locations: [
    {
      id: "aukstaitija-battle-mound",
      name: "Aukštaitija Battle Mound",
      coordinates: [55.6, 25.6],
      region: "Lithuania",
      description: "A prominent earthen mound in Aukštaitija used as an assembly point before military campaigns, associated with the war goddess Junda.",
      siteType: "Mythic hills / burial mounds",
      aura: "sky",
      deity: "junda",
      significance: "Warriors gathered at this mound before battle to make weapons offerings and invoke Junda for victory, and returned to offer spoils after successful campaigns.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania", lt: "Lietuva", lv: "Lietuva" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "19th Century (Reconstructed)", lt: "XIX a. (rekonstruotas)", lv: "19. gadsimts (rekonstruēts)" },
  references: [
    "Narbutt, Teodor: Dzieje starożytne narodu litewskiego (1835)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 4 (2005)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const kovasMeta: DeityMeta = {
  slug: "kovas",
  name: "Kovas",
  altNames: { en: "Kovas", lt: "Kovas", lv: "Kovas" },
  domain: "God",
  epithet: {
    en: "God of War and Combat",
    lt: "Karo ir kovos dievas",
    lv: "Kara un cīņas dievs",
  },
  summary: {
    en: "Kovas is the Lithuanian god of war and combat, whose name is synonymous with struggle and the month of March — the traditional start of the Baltic campaign season.",
    lt: "Kovas yra lietuvių karo ir kovos dievas, kurio vardas reiškia kovą ir kovo mėnesį – tradicinę karo žygių pradžią.",
    lv: "Kovas ir lietuviešu kara un cīņas dievs, kura vārds ir sinonīms cīņai un marta mēnesim — tradicionālā karagājienu sākuma laikam.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["War", "Combat", "March", "Military valor"],
  symbols: [
    { label: "Sacred symbols", detail: "Sword, Rook bird, Spear, Warhorse" },
  ],
  locations: [
    {
      id: "kernave-war-hillfort",
      name: "Kernavė Hill Fort Battlefield",
      coordinates: [54.88, 24.83],
      region: "Lithuania",
      description: "The ancient hillforts of Kernavė used as military assembly and command points, sacred to Kovas the god of war and combat.",
      siteType: "Sacred hilltops",
      aura: "sky",
      deity: "kovas",
      significance: "Lithuanian warriors consecrated their weapons here before spring campaigns, calling on Kovas whose name means both 'combat' and the fighting month of March.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const linksmineMeta: DeityMeta = {
  slug: "linksmine",
  name: "Linksmine",
  altNames: { en: "Linksmine", lt: "Linksminė", lv: "Linksmine" },
  domain: "God",
  epithet: {
    en: "Lady of Joy and Merriment",
    lt: "Džiaugsmo ir linksmumo deivė",
    lv: "Prieka un jautrības dieviete",
  },
  summary: {
    en: "Linksminė is the Lithuanian goddess of happiness and merriment, invoked at weddings and harvest festivals to ensure joyful atmospheres and the divine blessing of laughter.",
    lt: "Linksminė yra lietuvių džiaugsmo deivė, šaukiama per vestuves ir derliaus šventes, kad namai spindėtų šviesa ir daina.",
    lv: "Linksminė ir lietuviešu prieka un jautrības dieviete, ko piesauca kāzās un ražas svētkos.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Joy", "Happiness", "Merriment", "Song"],
  symbols: [
    { label: "Sacred symbols", detail: "Smile, Wine cup, Song, Sunrays" },
  ],
  locations: [
    {
      id: "zemaitija-festival-ground",
      name: "Žemaitija Communal Festival Ground",
      coordinates: [55.95, 22.35],
      region: "Lithuania",
      description: "An open village gathering ground in Samogitia used for wedding feasts, harvest celebrations, and song festivals honoring Linksminė.",
      siteType: "Communal feast sites",
      aura: "amber",
      deity: "linksmine",
      significance: "At weddings and harvest festivals, communities sang and danced on this green in honor of Linksminė, believing her presence filled the air with blessed laughter.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const rasaMeta: DeityMeta = {
  slug: "rasa",
  name: "Rasa",
  altNames: { en: "Rasa", lt: "Rasa", lv: "Rasa" },
  domain: "God",
  epithet: {
    en: "Goddess of Morning Dew",
    lt: "Ryto rasos deivė",
    lv: "Rīta rasas dieviete",
  },
  summary: {
    en: "Rasa is the Baltic goddess of morning dew and dawn freshness, a daughter of the Sun goddess Saulė who purifies and nourishes summer vegetation.",
    lt: "Rasa yra baltų ryto rasos deivė, Saulės dukra, kuri prausdama gamtą suteikia jai gijamąją galią.",
    lv: "Rasa ir baltu rīta rasas dieviete, Saules meita, kas mazgā un atjauno vasaras augu pasauli.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Dew", "Dawn", "Purification", "Vegetation"],
  symbols: [
    { label: "Sacred symbols", detail: "Water drop, Flower petal, Dawn light, Silver bowl" },
  ],
  locations: [
    {
      id: "aukstaitija-midsummer-meadow",
      name: "Aukštaitija Midsummer Dew Meadow",
      coordinates: [55.65, 25.3],
      region: "Lithuania",
      description: "A dew-rich meadow in Aukštaitija where young people rolled in the morning dew on Rasos (St. John's Eve) to absorb Rasa's healing power.",
      siteType: "Seasonal festival locations",
      aura: "green",
      deity: "rasa",
      significance: "On midsummer dawn, women washed their faces in meadow dew gathered in silver bowls, believing Rasa's blessing purified skin and healed ailments for the coming year.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Latvia", lt: "Lietuva, Latvija", lv: "Lietuva, Latvija" },
  tribe: { en: "All Baltic tribes", lt: "Visos baltų gentys", lv: "Visas baltu ciltis" },
  period: { en: "Ancient Origins", lt: "Seniausi laikai", lv: "Senākais periods" },
  references: [
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 4 (2005)",
    "Barons, Krišjānis: Latvju dainas (1894–1915)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const gardaitisMeta: DeityMeta = {
  slug: "gardaitis",
  name: "Gardaitis",
  altNames: { en: "Gardaitis", lt: "Gardaitis", lv: "Gardaitis" },
  domain: "God",
  epithet: {
    en: "Protector of Boats and Sailors",
    lt: "Laivų ir jūreivių globėjas",
    lv: "Laivu un jūrnieku aizbildnis",
  },
  summary: {
    en: "Gardaitis is the Lithuanian deity of boats and sailors, invoked during storms to ensure the safety of vessels and their crews on coastal and maritime voyages.",
    lt: "Gardaitis yra lietuvių laivų ir jūreivių dievas, šaukiamas audros metu, saugantis laivus ir įgulas nuo pavojų vandenyse.",
    lv: "Gardaitis ir lietuviešu laivu un jūrnieku dievs, ko piesauca vētrās, lai nodrošinātu kuģu un to apkalpes drošību.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Boats", "Sailors", "Sea voyages", "Wind"],
  symbols: [
    { label: "Sacred symbols", detail: "Ship, Sail, Windbag, Sea-stars" },
  ],
  locations: [
    {
      id: "klaipeda-sailors-harbor",
      name: "Klaipėda Sailors' Shrine Harbor",
      coordinates: [55.7, 21.12],
      region: "Lithuania",
      description: "The harbor shore at Klaipėda (Memel) where Baltic sailors offered prayers and ship models to Gardaitis before setting out to sea.",
      siteType: "Springs, rivers, lakes with cult significance",
      aura: "mist",
      deity: "gardaitis",
      significance: "Sailors invoked Gardaitis at the water's edge before departing, leaving miniature boat offerings to ensure safe passage and protection from storms.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Coastal / Samogitia)", lt: "Lietuva (pajūrys / Žemaitija)", lv: "Lietuva (piekraste / Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians, Curonians", lt: "Lietuviai, žemaičiai, kuršiai", lv: "Lietuvieši, žemaiši, kurši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const ganiklisMeta: DeityMeta = {
  slug: "ganiklis",
  name: "Ganiklis",
  altNames: { en: "Ganiklis", lt: "Ganiklis", lv: "Ganiklis" },
  domain: "God",
  epithet: {
    en: "Master of Shepherds",
    lt: "Piemenų globėjas",
    lv: "Ganu saimnieks",
  },
  summary: {
    en: "Ganiklis is the Lithuanian deity of shepherds and livestock grazing, invoked to ensure animals were not lost or attacked by wolves during the pasturing season.",
    lt: "Ganiklis yra lietuvių piemenų ir ganymo dievas, šaukiamas piemens apsaugai ir gyvulių saugumui ganymo laiku.",
    lv: "Ganiklis ir lietuviešu ganu un lopu ganīšanas dievs, ko piesauca, lai lopus sargātu no vilkiem un pazušanas.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Shepherds", "Livestock", "Grazing", "Pastures"],
  symbols: [
    { label: "Sacred symbols", detail: "Shepherd's horn, Staff, Sheep, Cowbell" },
  ],
  locations: [
    {
      id: "samogitia-herding-pasture",
      name: "Samogitian Herding Pasture Shrine",
      coordinates: [55.85, 22.6],
      region: "Lithuania",
      description: "A hillock at the edge of common pasture land in Samogitia where shepherds gathered to invoke Ganiklis at the start of the herding season.",
      siteType: "Field altars",
      aura: "green",
      deity: "ganiklis",
      significance: "Each spring, shepherds blew their horns three times at this pasture stone and left bread offerings to ensure Ganiklis would protect their flocks from wolves and straying.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const javineMeta: DeityMeta = {
  slug: "javine",
  name: "Javine",
  altNames: { en: "Javine", lt: "Javinė", lv: "Javine" },
  domain: "God",
  epithet: {
    en: "Goddess of Grain and Barns",
    lt: "Javų ir kluono deivė",
    lv: "Labības un rijas dieviete",
  },
  summary: {
    en: "Javinė is the Lithuanian deity who protects harvested grain and the threshing barn, guarding the stored bounty against rot, fire, and dark spirits until the next sowing.",
    lt: "Javinė yra lietuvių deivė, saugojanti nupjautus javus ir klojimą nuo drėgmės, ugnies ir piktųjų dvasių.",
    lv: "Javinė ir lietuviešu dieviete, kas sargā novāktus labības kūļus un rijā glabātās graudu krājumus.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Grain", "Harvest", "Barns", "Food preservation"],
  symbols: [
    { label: "Sacred symbols", detail: "Wheat sheaf, Wooden barn, Sickle" },
  ],
  locations: [
    {
      id: "zemaitija-grain-barn",
      name: "Žemaitija Threshing Barn Shrine",
      coordinates: [56.0, 22.2],
      region: "Lithuania",
      description: "A traditional wooden threshing barn (kluonas) in Samogitia dedicated to Javinė, protector of stored grain and dried sheaves.",
      siteType: "Household ritual sites",
      aura: "amber",
      deity: "javine",
      significance: "After harvest, the first grain bundle was placed in the barn's corner as an offering to Javinė, ensuring the stored grain would last through winter without rot or pest.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Samogitia", lt: "Lietuva, Žemaitija", lv: "Lietuva, Žemaitija" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "Medieval to 18th Century", lt: "Viduramžiai – XVIII a.", lv: "Viduslaiki – 18. gadsimts" },
  references: [
    "Dundulienė, Pranė: Gyvūnai ir augalai lietuvių mitologijoje (1983)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
    "Ruigys, Pilypas: Littauisch-Deutsches Lexikon (1747)",
  ],
};

export const geguteMeta: DeityMeta = {
  slug: "gegute",
  name: "Gegute",
  altNames: { en: "Gegute", lt: "Gegutė", lv: "Dzeguze" },
  domain: "God",
  epithet: {
    en: "Oracle Cuckoo of Fate",
    lt: "Likimo pranašė gegutė",
    lv: "Likteņa vēstnese dzeguze",
  },
  summary: {
    en: "Gegutė is the sacred cuckoo bird in Baltic mythology, an avatar and oracle of the fate goddess Laima, whose call predicts life spans, fortune, and the seasons.",
    lt: "Gegutė yra šventas paukštis lietuvių mitologijoje, likimo deivės Laimos pranašė, kurios kukavimas skelbia ateitį.",
    lv: "Dzeguze ir svēts putns baltu mitoloģijā, Laimas vēstnese, kuras dziesma paredz mūža ilgumu un likteni.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Fate", "Prophecy", "Spring", "Transformation"],
  symbols: [
    { label: "Sacred symbols", detail: "Cuckoo bird, Spring branch, Morning shadow" },
  ],
  locations: [
    {
      id: "aukstaitija-cuckoo-oak",
      name: "Aukštaitija Sacred Cuckoo Oak",
      coordinates: [55.58, 25.5],
      region: "Lithuania",
      description: "A great old oak in Aukštaitija where the first cuckoo call of spring was listened to as a divine oracle of Laima's fate decree.",
      siteType: "Sacred groves",
      aura: "green",
      deity: "gegute",
      significance: "Each spring, people gathered beneath this oak to count the cuckoo's calls, which foretold years of life remaining, fortune, and the success of the coming harvest.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Latvia", lt: "Lietuva, Latvija", lv: "Lietuva, Latvija" },
  tribe: { en: "Lithuanians, Latvians, Prussians", lt: "Lietuviai, latviai, prūsai", lv: "Lietuvieši, latvieši, prūši" },
  period: { en: "Ancient Origins", lt: "Seniausi laikai", lv: "Senākais periods" },
  references: [
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "Beresnevičius, Gintaras: Lietuvių religija ir mitologija (2004)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const pergrubrijusMeta: DeityMeta = {
  slug: "pergrubrijus",
  name: "Pergrubrijus",
  altNames: { en: "Pergrubrijus", lt: "Pergrubrijus", lv: "Pergrubrijus" },
  domain: "God",
  epithet: {
    en: "Lord of Spring and the Greening Earth",
    lt: "Pavasario ir želdimo dievas",
    lv: "Pavasara un zaļuma dievs",
  },
  summary: {
    en: "Pergrubrijus is the Prussian and Lithuanian deity of spring who unlocks the frozen earth with his key, bringing forth the first greenery and blessing the new agricultural year.",
    lt: "Pergrubrijus yra prūsų ir lietuvių pavasario dievas, kuris raktu atrakina įšalusią žemę ir leidžia jai sužaliuoti.",
    lv: "Pergrubrijus ir prūšu un lietuviešu pavasara dievs, kas ar atslēgu atver sasalušo zemi un atved pirmo zaļumu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Spring", "Vegetation", "Fertility", "Earth awakening"],
  symbols: [
    { label: "Sacred symbols", detail: "Green sprout, Key, Plough, Birch branch" },
  ],
  locations: [
    {
      id: "prussia-spring-meadow",
      name: "Old Prussian Spring Awakening Meadow",
      coordinates: [54.6, 21.1],
      region: "Old Prussia",
      description: "A meadow in Old Prussia used for spring-opening ceremonies where Pergrubrijus was invoked to unlock the frozen earth.",
      siteType: "Seasonal festival locations",
      aura: "green",
      deity: "pergrubrijus",
      significance: "At the first thaw, priests performed a key-turning ritual at this meadow, symbolically unlocking winter's grip and welcoming Pergrubrijus to bring forth the first green shoots.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Prussia, Lithuania, Samogitia", lt: "Prūsija, Lietuva, Žemaitija", lv: "Prūsija, Lietuva, Žemaitija" },
  tribe: { en: "Prussians, Sudovians, Lithuanians", lt: "Prūsai, sūduviai, lietuviai", lv: "Prūši, sudavieši, lietuvieši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Sudovian Book (Suduviu knygele), 16th c.",
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

// ─── Batch 8 ─────────────────────────────────────────────────────────────────

export const indrajaMeta: DeityMeta = {
  slug: "indraja",
  name: "Indraja",
  altNames: { en: "Indraja", lt: "Indraja", lv: "Indraja" },
  domain: "God",
  epithet: {
    en: "Goddess of Jupiter",
    lt: "Jupiterio deivė",
    lv: "Jupitera dieviete",
  },
  summary: {
    en: "Indraja is the Lithuanian personification of the planet Jupiter, a daughter of the Sun goddess Saulė who adds her radiant light to the celestial family traveling through the sky.",
    lt: "Indraja yra lietuvių Jupiterio planetos personifikacija, Saulės deivės dukra, pridedanti savo spindesį dangaus palydai.",
    lv: "Indraja ir lietuviešu Jupitera planētas personifikācija, Saules dievietes meita, kas papildina debesu ģimenes mirdzumu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Jupiter", "Celestial light", "Cosmic order", "Planets"],
  symbols: [
    { label: "Sacred symbols", detail: "Bright star, Planetary light, Celestial sphere" },
  ],
  locations: [
    {
      id: "zuvintas-reed-marsh",
      name: "Žuvintas Lake Reed Marsh",
      coordinates: [54.35, 23.6],
      region: "Lithuania",
      description: "The reed-fringed shores of Žuvintas Lake in Dzūkija, a liminal landscape associated with celestial reflection and the deity Indraja.",
      siteType: "Springs, rivers, lakes with cult significance",
      aura: "sky",
      deity: "indraja",
      significance: "The still lake surface mirroring Jupiter's light at night was seen as Indraja's sacred domain, where cosmic light touched the earth's waters.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania", lt: "Lietuva", lv: "Lietuva" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const vaivaMeta: DeityMeta = {
  slug: "vaiva",
  name: "Vaiva",
  altNames: { en: "Vaiva", lt: "Vaiva", lv: "Varavīksne" },
  domain: "God",
  epithet: {
    en: "The Rainbow — Belt of Laima",
    lt: "Vaivorykštė — Laimos juosta",
    lv: "Varavīksne — Laimas josta",
  },
  summary: {
    en: "Vaiva is the personified rainbow in Baltic mythology, known as the Belt of Laima, appearing after storms to signal the return of celestial order and the blessing of life-giving water.",
    lt: "Vaiva yra baltų mitologijoje personifikuota vaivorykštė, Laimos juosta, rodanti po audros, kad dangaus tvarka atkurta.",
    lv: "Varavīksne ir personificēta varavīksne baltu mitoloģijā, Laimas josta, kas pēc vētras signalizē par debesu kārtības atjaunošanu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Rainbow", "Celestial bridge", "After-storm", "Water cycle"],
  symbols: [
    { label: "Sacred symbols", detail: "Rainbow arc, Seven-colored belt, Rain drop, Weaving loom" },
  ],
  locations: [
    {
      id: "lithuania-rainbow-hilltop",
      name: "Lithuanian Rainbow Hilltop Vista",
      coordinates: [55.5, 24.0],
      region: "Lithuania",
      description: "An open hilltop in central Lithuania from which the full arc of the rainbow could be seen after summer storms, regarded as Vaiva's celestial belt.",
      siteType: "Sacred hilltops",
      aura: "sky",
      deity: "vaiva",
      significance: "Communities gathered on this hilltop after storms to observe the rainbow and give thanks to Vaiva, interpreting its colors as a sign of Laima's renewed celestial order.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Latvia", lt: "Lietuva, Latvija", lv: "Lietuva, Latvija" },
  tribe: { en: "Lithuanians, Latvians", lt: "Lietuviai, latviai", lv: "Lietuvieši, latvieši" },
  period: { en: "Medieval to Present Folklore", lt: "Viduramžiai – šiuolaikinė tautosaka", lv: "Viduslaiki – mūsdienu folklora" },
  references: [
    "Basanavičius, Jonas: Lietuviškos pasakos (1898–1902)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
    "Dundulienė, Pranė: Gyvūnai ir augalai lietuvių mitologijoje (1983)",
  ],
};

export const bubilasMeta: DeityMeta = {
  slug: "bubilas",
  name: "Bubilas",
  altNames: { en: "Bubilas", lt: "Bubilas", lv: "Bubilas" },
  domain: "God",
  epithet: {
    en: "Bee-Master and Honey God",
    lt: "Bičių meistras ir medaus dievas",
    lv: "Bišu meistars un medus dievs",
  },
  summary: {
    en: "Bubilas is the Lithuanian god of bees, drones, and honey production, the masculine counterpart to Austėja, who presides over the hive's strength and the abundance of the mead harvest.",
    lt: "Bubilas yra lietuvių bičių, tranų ir medaus gausos dievas, vyriškasis Austėjos atitikmuo, rūpinantis avilio stiprumu ir midaus derliumi.",
    lv: "Bubilas ir lietuviešu bišu, tranu un medus ražošanas dievs, vīrišķais Austējas atbilsme, kas pārskata stropu spēku.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Bees", "Drones", "Honey", "Mead", "Hive"],
  symbols: [
    { label: "Sacred symbols", detail: "Bee, Honeycomb, Drone, Mead mug" },
  ],
  locations: [
    {
      id: "aukstaitija-apiary-meadow",
      name: "Aukštaitija Sacred Apiary Meadow",
      coordinates: [55.62, 25.45],
      region: "Lithuania",
      description: "A wildflower meadow in Aukštaitija where traditional log beehives were kept in sacred groves, tended under Bubilas's protection.",
      siteType: "Field altars",
      aura: "amber",
      deity: "bubilas",
      significance: "Beekeepers left honeycomb offerings at a sacred tree on the meadow's edge, invoking Bubilas to keep the drone population strong and the mead harvest abundant.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Aukštaitija / Samogitia)", lt: "Lietuva (Aukštaitija / Žemaitija)", lv: "Lietuva (Augšzeme / Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const mildaMeta: DeityMeta = {
  slug: "milda",
  name: "Milda",
  altNames: { en: "Milda", lt: "Milda", lv: "Milda" },
  domain: "God",
  epithet: {
    en: "Goddess of Love (Disputed)",
    lt: "Meilės deivė (ginčytina)",
    lv: "Mīlestības dieviete (apstrīdēts)",
  },
  summary: {
    en: "Milda is the purported Lithuanian goddess of love and beauty, a figure popularized by 19th-century Romantic historian Teodor Narbutt. Contemporary scholars classify her as a literary reconstruction without authentic pre-Christian sources.",
    lt: "Milda yra tariama lietuvių meilės ir grožio deivė, T. Narbyto XIX a. romantinė rekonstrukcija; šiuolaikiniai mokslininkai laiko ją neautentišku išradimu.",
    lv: "Milda ir apgalvotā lietuviešu mīlestības un skaistuma dieviete, 19. gadsimta romantiskā rekonstrukcija; mūsdienu pētnieki to uzskata par vēlāku literāru izgudrojumu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Love", "Beauty", "Courtship", "Spring"],
  symbols: [
    { label: "Sacred symbols", detail: "Myrtle, Dove, Heart, May flowers" },
  ],
  locations: [
    {
      id: "kaunas-love-garden",
      name: "Kaunas Spring Courtship Garden",
      coordinates: [54.9, 23.9],
      region: "Lithuania",
      description: "A garden and meadow near Kaunas associated in Romantic literature with the love goddess Milda, where May Day courtship dances were held.",
      siteType: "Seasonal festival locations",
      aura: "green",
      deity: "milda",
      significance: "In 19th-century Romantic tradition, young Lithuanians gathered in spring gardens to dance and seek partners, invoking Milda's name for blessings in love.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Romantic Literature)", lt: "Lietuva (romantinė literatūra)", lv: "Lietuva (romantiskā literatūra)" },
  tribe: { en: "Lithuanians", lt: "Lietuviai", lv: "Lietuvieši" },
  period: { en: "19th Century (Reconstructed / Disputed)", lt: "XIX a. (rekonstruotas / ginčytina)", lv: "19. gadsimts (rekonstruēts / apstrīdēts)" },
  references: [
    "Narbutt, Teodor: Dzieje starożytne narodu litewskiego (1835)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
    "Balsys, Rimantas: Lietuvių ir prūsų dievai, deivės, dvasios (2010)",
  ],
};

export const asviniaiMeta: DeityMeta = {
  slug: "asvieniai",
  name: "Asvieniai",
  altNames: { en: "Asvieniai", lt: "Ašvieniai", lv: "Dieva dēli" },
  domain: "God",
  epithet: {
    en: "The Divine Horse Twins",
    lt: "Dieviškieji arklių dvyniai",
    lv: "Dievišķie zirgu dvīņi",
  },
  summary: {
    en: "Ašvieniai are the Baltic divine horse twins who pull the chariot of the Sun goddess Saulė across the sky, guardians of the solar cycle, immortalized in the crossed horse-head roof finials of traditional Baltic homes.",
    lt: "Ašvieniai yra baltų dieviškieji arklių dvyniai, traukiantys Saulės vežimą per dangų ir saugantys namus, įamžinti tradicinių namų žirgeliais ant kraigo.",
    lv: "Dieva dēli ir baltu dievišķie zirgu dvīņi, kas velk Saules vezumu pāri debesīm, mūžinājuši krustoto zirgugalvu jumta rotājumos.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Solar chariot", "Horse twins", "Divine protection", "Dawn"],
  symbols: [
    { label: "Sacred symbols", detail: "Crossed horse heads, Chariot wheel, White horse, Rising sun" },
  ],
  locations: [
    {
      id: "lithuania-horse-shrine",
      name: "Lithuanian Horse Twins Sacred Stable",
      coordinates: [55.5, 24.1],
      region: "Lithuania",
      description: "A traditional horse stable adorned with crossed horse-head roof finials (žirgeliai), the sacred symbol of the Ašvieniai twins across Baltic lands.",
      siteType: "Household ritual sites",
      aura: "amber",
      deity: "asvieniai",
      significance: "The crossed wooden horse heads on the roof ridges of Lithuanian farmhouses were believed to embody the Ašvieniai twins, protecting the household from evil and channeling solar blessing.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Latvia", lt: "Lietuva, Latvija", lv: "Lietuva, Latvija" },
  tribe: { en: "All Baltic tribes", lt: "Visos baltų gentys", lv: "Visas baltu ciltis" },
  period: { en: "Proto-Baltic to Present", lt: "Protobaltiški laikai – dabartis", lv: "Protobaltu laiki – mūsdienas" },
  references: [
    "Dundulienė, Pranė: Gyvūnai ir augalai lietuvių mitologijoje (1983)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
    "Greimas, Algirdas Julius: Of Gods and Men (1992)",
  ],
};

export const erketusMeta: DeityMeta = {
  slug: "erketus",
  name: "Erketus",
  altNames: { en: "Erketus", lt: "Erketus", lv: "Erketus" },
  domain: "God",
  epithet: {
    en: "Spirit of Thorns and Protective Barriers",
    lt: "Erškėčių ir apsauginių kliūčių dvasia",
    lv: "Ērkšķu un aizsargbarjeru gars",
  },
  summary: {
    en: "Erketus is the Lithuanian spirit of thorns and briers, the divine guardian of protective hedges and natural barriers that separated the sacred farmstead from the wild forest beyond.",
    lt: "Erketus yra lietuvių erškėčių ir dygliuotų kliūčių dvasia, apsauginių gyvatvorių sargas, skiriančių šventą sodybą nuo laukinio miško.",
    lv: "Erketus ir lietuviešu ērkšķu un dzeloņu gars, aizsardzības dzīvžogu sargs, kas atdalīja sētu no savvaļas meža.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Thorns", "Briers", "Protective barriers", "Boundaries"],
  symbols: [
    { label: "Sacred symbols", detail: "Thorn, Brier, Barb, Defensive hedge, Hawthorn" },
  ],
  locations: [
    {
      id: "samogitia-thorn-hedge",
      name: "Samogitian Protective Thorn Hedge",
      coordinates: [55.92, 22.4],
      region: "Lithuania",
      description: "An ancient hawthorn hedge surrounding a Samogitian farmstead, maintained as a ritual boundary under the guardianship of Erketus.",
      siteType: "Household ritual sites",
      aura: "moss",
      deity: "erketus",
      significance: "The thorn hedge was never trimmed without a ritual offering to Erketus, who was believed to empower the natural barrier to repel harmful spirits from the sacred farmstead.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const veliuonaMeta: DeityMeta = {
  slug: "veliuona",
  name: "Veliuona",
  altNames: { en: "Veliuona", lt: "Veliuona", lv: "Veliuona" },
  domain: "God",
  epithet: {
    en: "Mistress of the Dead",
    lt: "Vėlių valdovė",
    lv: "Mirušo valdniece",
  },
  summary: {
    en: "Veliuona is the Lithuanian goddess of death and the realm of ancestral spirits, the solemn guardian who receives the departed and maintains the boundary between the living and the dead.",
    lt: "Veliuona yra lietuvių mirties ir protėvių vėlių karalystės deivė, iškilmingoji sargė, priimanti mirusius ir sauganti gyvenimo bei mirties ribą.",
    lv: "Veliuona ir lietuviešu nāves un senču garu valstības dieviete, svinīgā sargātāja, kas uztur robežu starp dzīvajiem un mirušajiem.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Death", "Ancestral spirits", "Underworld", "Funerary rites"],
  symbols: [
    { label: "Sacred symbols", detail: "Grave mound, Night sky, Spirit lights, Ancient tree" },
  ],
  locations: [
    {
      id: "veliuona-ancestor-mound",
      name: "Veliuona Ancestor Mound",
      coordinates: [55.08, 23.45],
      region: "Lithuania",
      description: "The historic mound at Veliuona town on the Nemunas River, associated with ancestral spirits and the goddess Veliuona who guards the realm of the dead.",
      siteType: "Mythic hills / burial mounds",
      aura: "mist",
      deity: "veliuona",
      significance: "The mound of Veliuona town was believed to be the earthly threshold to the spirit realm; ancestor festivals (Vėlinės) were held here with candle offerings to the departed.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Samogitia", lt: "Lietuva, Žemaitija", lv: "Lietuva, Žemaitija" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const lauksargisMeta: DeityMeta = {
  slug: "lauksargis",
  name: "Lauksargis",
  altNames: { en: "Lauksargis", lt: "Lauksargis", lv: "Lauku māte" },
  domain: "God",
  epithet: {
    en: "Guardian of the Fields",
    lt: "Laukų sargas",
    lv: "Lauku sargs",
  },
  summary: {
    en: "Lauksargis is the Baltic field guardian deity, protector of crops and agricultural boundaries, invoked before sowing to ensure the land's safety and the health of the harvest.",
    lt: "Lauksargis yra baltų laukų sargo dievybė, pasėlių ir žemės ribų globėjas, šaukiamas prieš sėją užtikrinti derliaus saugumą.",
    lv: "Lauksargis ir baltu lauku sargātājs, kultūraugu un lauksaimniecības robežu aizsargs, ko piesauca pirms sējas.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Fields", "Crops", "Boundaries", "Plowing", "Harvest protection"],
  symbols: [
    { label: "Sacred symbols", detail: "Plowshare, Boundary stone, Woven sheaf, Field lark" },
  ],
  locations: [
    {
      id: "lithuania-field-boundary",
      name: "Lithuanian Field Boundary Marker",
      coordinates: [55.45, 24.05],
      region: "Lithuania",
      description: "A ritual field boundary stone in central Lithuania where Lauksargis was invoked to protect crops and enforce the sacred borders of agricultural land.",
      siteType: "Ritual stones",
      aura: "green",
      deity: "lauksargis",
      significance: "Before each sowing, farmers walked the field perimeter offering grain and bread at each boundary stone, asking Lauksargis to guard against theft, blight, and trespass.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania, Latvia", lt: "Lietuva, Latvija", lv: "Lietuva, Latvija" },
  tribe: { en: "Lithuanians, Latvians", lt: "Lietuviai, latviai", lv: "Lietuvieši, latvieši" },
  period: { en: "Medieval to 18th Century", lt: "Viduramžiai – XVIII a.", lv: "Viduslaiki – 18. gadsimts" },
  references: [
    "Mažvydas, Martynas: Katekizmas (1547)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
    "Dundulienė, Pranė: Žemdirbystė lietuvių mitologijoje (1963)",
  ],
};

export const drebkulysMeta: DeityMeta = {
  slug: "drebkulys",
  name: "Drebkulys",
  altNames: { en: "Drebkulys", lt: "Drebkulys", lv: "Drebkulys" },
  domain: "God",
  epithet: {
    en: "Spirit of the Shivering Fever",
    lt: "Karštinės ir drebulio dvasia",
    lv: "Drudža drebēšanas gars",
  },
  summary: {
    en: "Drebkulys is the Lithuanian spirit of fever and chills, the personification of the shaking sickness recorded by Jan Łasicki, representing the archaic Baltic belief that every illness was governed by its own divine force.",
    lt: "Drebkulys yra lietuvių karštinės ir drebulio dvasia, krečiančios ligos personifikacija, užrašyta Jano Lasickio — liudijimas archajinio tikėjimo, kad kiekvieną ligą valdo savita dvasia.",
    lv: "Drebkulys ir lietuviešu drudža un drebuļa gars, locītavās kratošās slimības personifikācija pēc Jana Lasicija, kas atspoguļo senu baltu uzskatu par slimību garu varu.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Fever", "Chills", "Shivering", "Illness"],
  symbols: [
    { label: "Sacred symbols", detail: "Trembling hand, Pale face, Shivering figure" },
  ],
  locations: [
    {
      id: "samogitia-fever-bog",
      name: "Samogitian Fever Bog",
      coordinates: [55.88, 22.15],
      region: "Lithuania",
      description: "A damp, misty bog in Samogitia believed to be the dwelling of Drebkulys, the spirit of fever and chills, avoided by travelers especially at night.",
      siteType: "Sacrifice / offering sites",
      aura: "mist",
      deity: "drebkulys",
      significance: "Those afflicted with fever came to the bog edge to leave offerings — a piece of thread from their clothing — to appease Drebkulys and be released from the shaking sickness.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De Diis Samagitarum (1582; publ. 1615)",
    "Vėlius, Norbertas: Baltų religijos ir mitologijos šaltiniai, Vol. 2 (1996)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

export const apidemeMeta: DeityMeta = {
  slug: "apideme",
  name: "Apideme",
  altNames: { en: "Apideme", lt: "Apidėmė", lv: "Apidēme" },
  domain: "God",
  epithet: {
    en: "Guardian of the Homestead's Edge",
    lt: "Sodybos ribų saugotoja",
    lv: "Mājas robežu sargātāja",
  },
  summary: {
    en: "Apidėmė is the Lithuanian spirit of the homestead boundary, the divine guardian of fences and thresholds who was offered sacrifices when a family moved to ensure she would follow and protect the new farmstead.",
    lt: "Apidėmė yra lietuvių sodybos ribų dvasia, dieviškoji tvorų ir slenksčio sargė, kuriai aukojama kraustantis, kad ji sektų ir saugotų naują sodybą.",
    lv: "Apidēme ir lietuviešu mājas robežu gars, žogu un sliekšņa dievišķā sargātāja, kurai upuroja pārceļoties, lai viņa sekotu un sargātu jauno saimniecību.",
  },
  heroImage: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
  overlay: "rgba(80, 80, 60, 0.27)",
  accent: "#8a8a6a",
  keywords: ["Homestead", "Boundaries", "Fences", "Threshold", "Moving"],
  symbols: [
    { label: "Sacred symbols", detail: "Threshold, Fence gate, Corner stone, Rooster" },
  ],
  locations: [
    {
      id: "samogitia-homestead-boundary",
      name: "Samogitian Homestead Boundary Shrine",
      coordinates: [55.95, 22.28],
      region: "Lithuania",
      description: "The gate and fence perimeter of a traditional Samogitian homestead where Apidėmė was honored as the guardian of household boundaries.",
      siteType: "Household ritual sites",
      aura: "green",
      deity: "apideme",
      significance: "When a family moved to a new farmstead, they performed a ritual at each fence post asking Apidėmė to follow them and extend her boundary protection to their new home.",
    },
  ],
  gallery: [],
  materialLegacy: [],
  regionDetails: { en: "Lithuania (Samogitia)", lt: "Lietuva (Žemaitija)", lv: "Lietuva (Žemaitija)" },
  tribe: { en: "Lithuanians, Samogitians", lt: "Lietuviai, žemaičiai", lv: "Lietuvieši, žemaiši" },
  period: { en: "16th Century (Recorded)", lt: "XVI a. (užrašytas)", lv: "16. gadsimts (dokumentēts)" },
  references: [
    "Łasicki, Jan: De diis Samagitarum caeterisque Sarmatum (1582)",
    "Beresnevičius, Gintaras: Lietuvių religija ir mitologija (2004)",
    "VLE: Visuotinė lietuvių enciklopedija (vle.lt)",
  ],
};

